#!/usr/bin/env Rscript
#' ============================================================================
#' HTML REPORT GENERATOR for Validation Results
#' ============================================================================
#'
#' Reads .rds result files from the comprehensive validation scripts and
#' generates self-contained HTML reports with embedded CSS (no pandoc needed).
#'
#' USAGE:
#'   Rscript validation/generate_html_reports.R
#'
#' EXPECTS:
#'   - validation/results_centrality_comprehensive.rds
#'   - validation/results_communities_comprehensive.rds
#'   - validation/results_network_properties_comprehensive.rds
#'
#' OUTPUT:
#'   - validation/reports/centrality_validation.html
#'   - validation/reports/communities_validation.html
#'   - validation/reports/network_properties_validation.html
#'   - validation/reports/combined_validation.html
#'
#' ============================================================================

output_dir <- "validation/reports"
input_dir <- "validation"

if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

# ============================================================================
# CSS + HTML Helpers
# ============================================================================

css_style <- '
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         background: #f5f7fa; color: #333; line-height: 1.6; padding: 20px; }
  .container { max-width: 1100px; margin: 0 auto; }
  h1 { font-size: 1.8em; margin-bottom: 10px; color: #1a1a2e; }
  h2 { font-size: 1.3em; margin: 25px 0 10px; color: #1a1a2e; border-bottom: 2px solid #e0e0e0; padding-bottom: 5px; }
  .header { background: #1a1a2e; color: #fff; padding: 25px 30px; border-radius: 10px; margin-bottom: 20px; }
  .header h1 { color: #fff; }
  .header .meta { font-size: 0.9em; opacity: 0.8; margin-top: 5px; }
  .summary-cards { display: flex; gap: 15px; margin-bottom: 20px; flex-wrap: wrap; }
  .card { background: #fff; border-radius: 8px; padding: 20px; flex: 1; min-width: 200px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .card .label { font-size: 0.85em; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
  .card .value { font-size: 2em; font-weight: 700; margin-top: 5px; }
  .card .value.pass { color: #2ecc71; }
  .card .value.fail { color: #e74c3c; }
  .card .value.neutral { color: #3498db; }
  .progress-bar { background: #e0e0e0; border-radius: 10px; height: 12px; margin-top: 10px; overflow: hidden; }
  .progress-fill { height: 100%; border-radius: 10px; transition: width 0.3s; }
  .progress-fill.green { background: linear-gradient(90deg, #27ae60, #2ecc71); }
  .progress-fill.red { background: linear-gradient(90deg, #c0392b, #e74c3c); }
  .progress-fill.yellow { background: linear-gradient(90deg, #f39c12, #f1c40f); }
  table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px;
          overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 20px; }
  th { background: #2c3e50; color: #fff; padding: 10px 14px; text-align: left; font-size: 0.85em;
       text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 8px 14px; border-bottom: 1px solid #eee; font-size: 0.9em; }
  tr:last-child td { border-bottom: none; }
  tr:hover { background: #f8f9fa; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; font-weight: 600; }
  .badge-pass { background: #d4edda; color: #155724; }
  .badge-fail { background: #f8d7da; color: #721c24; }
  .badge-warn { background: #fff3cd; color: #856404; }
  .badge-skip { background: #e2e3e5; color: #383d41; }
  .config-box { background: #fff; border-radius: 8px; padding: 15px 20px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 20px; font-size: 0.9em; }
  .config-box code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-family: monospace; }
  .footer { text-align: center; color: #999; font-size: 0.8em; margin-top: 30px; padding: 15px; }
  .section-link { display: inline-block; background: #3498db; color: #fff; padding: 8px 16px;
                  border-radius: 5px; text-decoration: none; margin: 5px; font-size: 0.9em; }
  .section-link:hover { background: #2980b9; }
  .no-data { background: #fff3cd; color: #856404; padding: 20px; border-radius: 8px;
             text-align: center; margin: 20px 0; }
</style>
'

html_head <- function(title) {
  sprintf('<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>%s</title>\n%s\n</head>\n<body>\n<div class="container">\n',
          title, css_style)
}

html_tail <- function() {
  sprintf('<div class="footer">Generated by cograph validation suite &mdash; %s</div>\n</div>\n</body>\n</html>',
          format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
}

html_header <- function(title, subtitle = "") {
  sub_html <- if (nzchar(subtitle)) sprintf('<div class="meta">%s</div>', subtitle) else ""
  sprintf('<div class="header"><h1>%s</h1>%s</div>\n', title, sub_html)
}

progress_bar_color <- function(pct) {
  if (pct >= 99) "green" else if (pct >= 80) "yellow" else "red"
}

html_summary_cards <- function(total, passed, failed, max_diff = NULL) {
  pct <- if (total > 0) round(100 * passed / total, 1) else 0
  bar_color <- progress_bar_color(pct)

  diff_card <- ""
  if (!is.null(max_diff) && !is.na(max_diff)) {
    diff_card <- sprintf(
      '<div class="card"><div class="label">Max Difference</div><div class="value neutral">%.2e</div></div>',
      max_diff)
  }

  sprintf(
    '<div class="summary-cards">
  <div class="card"><div class="label">Total Tests</div><div class="value neutral">%d</div></div>
  <div class="card"><div class="label">Passed</div><div class="value pass">%d</div></div>
  <div class="card"><div class="label">Failed</div><div class="value fail">%d</div></div>
  <div class="card"><div class="label">Pass Rate</div><div class="value %s">%.1f%%</div>
    <div class="progress-bar"><div class="progress-fill %s" style="width:%.1f%%"></div></div>
  </div>
  %s
</div>\n',
    total, passed, failed,
    if (pct >= 99) "pass" else "fail", pct,
    bar_color, pct,
    diff_card)
}

html_table <- function(df, highlight_col = NULL) {
  if (is.null(df) || nrow(df) == 0) return('<div class="no-data">No data available</div>\n')

  header <- paste0("<tr>", paste0("<th>", colnames(df), "</th>", collapse = ""), "</tr>")

  rows <- vapply(seq_len(nrow(df)), function(i) {
    cells <- vapply(seq_len(ncol(df)), function(j) {
      val <- as.character(df[i, j])
      if (!is.null(highlight_col) && colnames(df)[j] == highlight_col) {
        if (grepl("100", val) || grepl("PASS", val, ignore.case = TRUE)) {
          val <- sprintf('<span class="badge badge-pass">%s</span>', val)
        } else if (grepl("FAIL", val, ignore.case = TRUE) || grepl("^0", val)) {
          val <- sprintf('<span class="badge badge-fail">%s</span>', val)
        } else if (grepl("SKIP", val, ignore.case = TRUE)) {
          val <- sprintf('<span class="badge badge-skip">%s</span>', val)
        }
      }
      sprintf("<td>%s</td>", val)
    }, character(1))
    paste0("<tr>", paste0(cells, collapse = ""), "</tr>")
  }, character(1))

  sprintf("<table>\n<thead>%s</thead>\n<tbody>\n%s\n</tbody>\n</table>\n",
          header, paste0(rows, collapse = "\n"))
}

html_config_box <- function(config) {
  items <- vapply(names(config), function(nm) {
    sprintf("<strong>%s:</strong> <code>%s</code>", nm, as.character(config[[nm]]))
  }, character(1))
  sprintf('<div class="config-box">%s</div>\n', paste(items, collapse = " &nbsp;|&nbsp; "))
}


# ============================================================================
# Report 1: Centrality Validation
# ============================================================================

generate_centrality_report <- function() {
  rds_file <- file.path(input_dir, "results_centrality_comprehensive.rds")
  if (!file.exists(rds_file)) {
    cat("  [SKIP] Centrality results not found:", rds_file, "\n")
    return(invisible(NULL))
  }

  data <- readRDS(rds_file)
  out <- file.path(output_dir, "centrality_validation.html")

  summary_df <- data$summary
  failures <- data$failures
  config <- data$config

  total <- sum(summary_df$passed) + sum(summary_df$failed)
  passed <- sum(summary_df$passed)
  failed <- sum(summary_df$failed)
  max_diff <- max(summary_df$max_diff, na.rm = TRUE)

  # Map each measure to its external reference function
  ref_map <- c(
    degree_all = "igraph::degree(mode='all')",
    degree_in = "igraph::degree(mode='in')",
    degree_out = "igraph::degree(mode='out')",
    strength_all = "igraph::strength(mode='all')",
    strength_in = "igraph::strength(mode='in')",
    strength_out = "igraph::strength(mode='out')",
    betweenness = "igraph::betweenness()",
    betweenness_cutoff2 = "igraph::betweenness(cutoff=2)",
    betweenness_noloops = "igraph::betweenness() [no loops]",
    betweenness_unweighted = "igraph::betweenness(weights=NULL)",
    closeness_all = "igraph::closeness(mode='all')",
    closeness_in = "igraph::closeness(mode='in')",
    closeness_out = "igraph::closeness(mode='out')",
    closeness_all_norm = "igraph::closeness(normalized=TRUE)",
    closeness_in_norm = "igraph::closeness(normalized=TRUE)",
    closeness_out_norm = "igraph::closeness(normalized=TRUE)",
    closeness_all_cutoff2 = "igraph::closeness(cutoff=2)",
    closeness_in_cutoff2 = "igraph::closeness(cutoff=2)",
    closeness_out_cutoff2 = "igraph::closeness(cutoff=2)",
    eigenvector = "igraph::eigen_centrality()",
    pagerank = "igraph::page_rank(damping=0.85)",
    pagerank_d05 = "igraph::page_rank(damping=0.5)",
    pagerank_d95 = "igraph::page_rank(damping=0.95)",
    pagerank_personalized = "igraph::page_rank(personalized=...)",
    authority = "igraph::authority_score()",
    hub = "igraph::hub_score()",
    eccentricity_all = "igraph::eccentricity(mode='all')",
    eccentricity_in = "igraph::eccentricity(mode='in')",
    eccentricity_out = "igraph::eccentricity(mode='out')",
    coreness_all = "igraph::coreness(mode='all')",
    coreness_in = "igraph::coreness(mode='in')",
    coreness_out = "igraph::coreness(mode='out')",
    constraint = "igraph::constraint()",
    constraint_unweighted = "igraph::constraint(weights=NULL)",
    transitivity_local = "igraph::transitivity(type='local')",
    transitivity_global = "igraph::transitivity(type='global')",
    transitivity_barrat = "igraph::transitivity(type='barrat')",
    harmonic_all = "igraph::harmonic_centrality(mode='all')",
    harmonic_in = "igraph::harmonic_centrality(mode='in')",
    harmonic_out = "igraph::harmonic_centrality(mode='out')",
    harmonic_all_norm = "igraph::harmonic_centrality() / max",
    harmonic_in_norm = "igraph::harmonic_centrality() / max",
    harmonic_out_norm = "igraph::harmonic_centrality() / max",
    harmonic_all_cutoff2 = "igraph::harmonic_centrality(cutoff=2)",
    harmonic_in_cutoff2 = "igraph::harmonic_centrality(cutoff=2)",
    harmonic_out_cutoff2 = "igraph::harmonic_centrality(cutoff=2)",
    alpha = "igraph::alpha_centrality()",
    power = "igraph::power_centrality()",
    subgraph = "igraph::subgraph_centrality()",
    diffusion_lam0.5 = "centiserve::diffusion.degree(lambda=0.5)",
    diffusion_lam1.0 = "centiserve::diffusion.degree(lambda=1.0)",
    diffusion_lam2.5 = "centiserve::diffusion.degree(lambda=2.5)",
    diffusion_in = "centiserve::diffusion.degree(mode='in')",
    diffusion_out = "centiserve::diffusion.degree(mode='out')",
    leverage_all = "centiserve::leverage(mode='all')",
    leverage_in = "centiserve::leverage(mode='in')",
    leverage_out = "centiserve::leverage(mode='out')",
    kreach_k1 = "centiserve::geokpath(k=1)",
    kreach_k2 = "centiserve::geokpath(k=2)",
    kreach_k5 = "centiserve::geokpath(k=5)",
    laplacian = "centiserve::laplacian()",
    current_flow_closeness = "centiserve::closeness.currentflow()",
    current_flow_betweenness = "structural validation (bounds)",
    load = "sna::loadcent()",
    percolation_uniform = "igraph::betweenness() / ((n-1)*(n-2))",
    voterank = "structural validation (bounds)",
    edge_betweenness = "igraph::edge_betweenness()",
    measures_multi_structure = "structural validation (columns)"
  )

  # Add reference column to summary
  summary_df$validated_against <- vapply(summary_df$measure, function(m) {
    if (m %in% names(ref_map)) ref_map[[m]] else "—"
  }, character(1))

  html <- paste0(
    html_head("Centrality Validation Report"),
    html_header("Centrality Validation",
                sprintf("cograph vs igraph / centiserve / sna | %s", data$timestamp)),
    html_config_box(config),
    html_summary_cards(total, passed, failed, max_diff),

    "<h2>Results by Measure</h2>\n",
    html_table(summary_df[, c("measure", "validated_against", "passed", "failed", "max_diff", "pass_rate")],
               highlight_col = "pass_rate")
  )

  if (length(failures) > 0) {
    fail_df <- do.call(rbind, lapply(failures, function(f) {
      data.frame(
        Test = f$test_id,
        Measure = f$measure,
        Reason = f$reason,
        Nodes = f$network$n_nodes,
        Edges = f$network$n_edges,
        Directed = f$network$directed,
        Weighted = f$network$weighted,
        stringsAsFactors = FALSE
      )
    }))
    html <- paste0(html, "<h2>Failure Details</h2>\n", html_table(fail_df))
  }

  html <- paste0(html, html_tail())
  writeLines(html, out)
  cat("  [OK] Centrality report:", out, "\n")
  invisible(out)
}


# ============================================================================
# Report 2: Communities Validation
# ============================================================================

generate_communities_report <- function() {
  rds_file <- file.path(input_dir, "results_communities_comprehensive.rds")
  if (!file.exists(rds_file)) {
    cat("  [SKIP] Communities results not found:", rds_file, "\n")
    return(invisible(NULL))
  }

  data <- readRDS(rds_file)
  out <- file.path(output_dir, "communities_validation.html")

  summary_df <- data$summary
  failures <- data$failures
  config <- data$config

  total <- sum(summary_df$passed) + sum(summary_df$failed)
  passed <- sum(summary_df$passed)
  failed <- sum(summary_df$failed)

  # Map each community algorithm to its igraph reference
  comm_ref_map <- c(
    fast_greedy = "igraph::cluster_fast_greedy()",
    walktrap = "igraph::cluster_walktrap()",
    edge_betweenness = "igraph::cluster_edge_betweenness()",
    leading_eigenvector = "igraph::cluster_leading_eigen()",
    louvain = "igraph::cluster_louvain()",
    leiden = "igraph::cluster_leiden()",
    infomap = "igraph::cluster_infomap()",
    label_propagation = "igraph::cluster_label_prop()",
    spinglass = "igraph::cluster_spinglass()",
    optimal = "igraph::cluster_optimal()",
    fluid = "modularity + n_communities validation",
    consensus = "modularity + community count validation",
    params = "parameter variation monotonicity",
    directed = "igraph community algorithms",
    weighted = "igraph community algorithms",
    compare = "igraph::compare() (NMI/VI/Rand)",
    helpers = "igraph membership/modularity"
  )

  summary_df$validated_against <- vapply(summary_df$test_group, function(m) {
    if (m %in% names(comm_ref_map)) comm_ref_map[[m]] else "—"
  }, character(1))

  html <- paste0(
    html_head("Communities Validation Report"),
    html_header("Communities Validation",
                sprintf("All 12 algorithms + parameter variations | %s", data$timestamp)),
    html_config_box(config),
    html_summary_cards(total, passed, failed),

    "<h2>Results by Algorithm / Test</h2>\n",
    html_table(summary_df[, c("test_group", "validated_against", "passed", "failed", "pass_rate")],
               highlight_col = "pass_rate")
  )

  if (length(failures) > 0) {
    fail_df <- do.call(rbind, lapply(failures, function(f) {
      data.frame(
        Test = f$test_id,
        Group = if (!is.null(f$group)) f$group else "",
        Reason = f$reason,
        Network = if (!is.null(f$network_name)) f$network_name else "",
        stringsAsFactors = FALSE
      )
    }))
    html <- paste0(html, "<h2>Failure Details</h2>\n", html_table(fail_df))
  }

  html <- paste0(html, html_tail())
  writeLines(html, out)
  cat("  [OK] Communities report:", out, "\n")
  invisible(out)
}


# ============================================================================
# Report 3: Network Properties Validation
# ============================================================================

generate_network_properties_report <- function() {
  rds_file <- file.path(input_dir, "results_network_properties_comprehensive.rds")
  if (!file.exists(rds_file)) {
    cat("  [SKIP] Network properties results not found:", rds_file, "\n")
    return(invisible(NULL))
  }

  data <- readRDS(rds_file)
  out <- file.path(output_dir, "network_properties_validation.html")

  summary_df <- data$summary
  failures <- data$failures
  config <- data$config

  total <- sum(summary_df$passed) + sum(summary_df$failed)
  passed <- sum(summary_df$passed)
  failed <- sum(summary_df$failed)
  max_diff <- if ("max_diff" %in% names(summary_df)) max(summary_df$max_diff, na.rm = TRUE) else NA

  netprop_ref_map <- c(
    known_graphs = "igraph (girth, radius, connectivity, cliques, cuts, bridges, efficiency)",
    simulated = "igraph (girth, radius, connectivity, cliques, cuts, bridges, efficiency)",
    directed = "igraph::radius(mode='out'), igraph::girth()",
    weighted = "igraph global_efficiency, vertex_connectivity",
    network_summary = "igraph (node/edge count, density, diameter, girth, radius, degree)",
    degree_distribution = "igraph::degree() frequency table",
    small_world = "igraph transitivity + mean_distance ratio",
    rich_club = "igraph rich_club coefficient"
  )

  summary_df$validated_against <- vapply(summary_df$category, function(m) {
    if (m %in% names(netprop_ref_map)) netprop_ref_map[[m]] else "—"
  }, character(1))

  html <- paste0(
    html_head("Network Properties Validation Report"),
    html_header("Network Properties Validation",
                sprintf("Known graphs + simulated networks | %s", data$timestamp)),
    html_config_box(config),
    html_summary_cards(total, passed, failed, max_diff),

    "<h2>Results by Category</h2>\n",
    html_table(summary_df[, c("category", "validated_against", "passed", "failed",
                               intersect("max_diff", names(summary_df)), "pass_rate"), drop = FALSE],
               highlight_col = "pass_rate")
  )

  if (length(failures) > 0) {
    fail_df <- do.call(rbind, lapply(failures, function(f) {
      data.frame(
        Test = f$test_id,
        Category = if (!is.null(f$category)) f$category else "",
        Metric = if (!is.null(f$metric)) f$metric else "",
        Reason = f$reason,
        stringsAsFactors = FALSE
      )
    }))
    html <- paste0(html, "<h2>Failure Details</h2>\n", html_table(fail_df))
  }

  html <- paste0(html, html_tail())
  writeLines(html, out)
  cat("  [OK] Network properties report:", out, "\n")
  invisible(out)
}


# ============================================================================
# Report 4: Combined Dashboard
# ============================================================================

generate_combined_report <- function() {
  out <- file.path(output_dir, "combined_validation.html")

  # Read all available results
  sections <- list()
  overall_total <- 0
  overall_passed <- 0
  overall_failed <- 0

  rds_files <- list(
    centrality = file.path(input_dir, "results_centrality_comprehensive.rds"),
    communities = file.path(input_dir, "results_communities_comprehensive.rds"),
    network_properties = file.path(input_dir, "results_network_properties_comprehensive.rds")
  )

  report_links <- list(
    centrality = "centrality_validation.html",
    communities = "communities_validation.html",
    network_properties = "network_properties_validation.html"
  )

  section_labels <- list(
    centrality = "Centrality Measures",
    communities = "Community Detection",
    network_properties = "Network Properties"
  )

  for (name in names(rds_files)) {
    f <- rds_files[[name]]
    if (file.exists(f)) {
      data <- readRDS(f)
      s <- data$summary
      p <- sum(s$passed)
      fl <- sum(s$failed)
      t <- p + fl
      pct <- if (t > 0) round(100 * p / t, 1) else 0
      sections[[name]] <- list(
        label = section_labels[[name]],
        total = t, passed = p, failed = fl, pct = pct,
        report = report_links[[name]],
        timestamp = data$timestamp,
        config = data$config
      )
      overall_total <- overall_total + t
      overall_passed <- overall_passed + p
      overall_failed <- overall_failed + fl
    }
  }

  if (length(sections) == 0) {
    cat("  [SKIP] No result files found for combined report\n")
    return(invisible(NULL))
  }

  overall_pct <- if (overall_total > 0) round(100 * overall_passed / overall_total, 1) else 0

  html <- paste0(
    html_head("cograph Validation Dashboard"),
    html_header("cograph Comprehensive Validation Dashboard",
                sprintf("Combined results from all validation suites | %s",
                        format(Sys.time(), "%Y-%m-%d %H:%M:%S"))),
    html_summary_cards(overall_total, overall_passed, overall_failed),
    "<h2>Section Reports</h2>\n"
  )

  # Section summary table
  section_df <- do.call(rbind, lapply(sections, function(s) {
    data.frame(
      Suite = s$label,
      Total = s$total,
      Passed = s$passed,
      Failed = s$failed,
      pass_rate = sprintf("%.1f%%", s$pct),
      stringsAsFactors = FALSE
    )
  }))
  html <- paste0(html, html_table(section_df, highlight_col = "pass_rate"))

  # Links to individual reports
  html <- paste0(html, '<div style="text-align:center; margin: 20px 0;">\n')
  for (s in sections) {
    html <- paste0(html, sprintf('<a class="section-link" href="%s">%s Report</a>\n',
                                 s$report, s$label))
  }
  html <- paste0(html, "</div>\n")

  # Per-section detail
  for (name in names(sections)) {
    s <- sections[[name]]
    f <- rds_files[[name]]
    data <- readRDS(f)

    html <- paste0(html, sprintf("<h2>%s</h2>\n", s$label))

    if (!is.null(data$config)) {
      html <- paste0(html, html_config_box(data$config))
    }

    # Show the per-measure summary table
    display_cols <- intersect(
      c("measure", "test_group", "category", "validated_against",
        "passed", "failed", "max_diff", "pass_rate"),
      names(data$summary)
    )
    html <- paste0(html, html_table(data$summary[, display_cols, drop = FALSE],
                                    highlight_col = "pass_rate"))

    # Show up to 10 failures
    if (length(data$failures) > 0) {
      n_show <- min(10, length(data$failures))
      fail_items <- vapply(data$failures[seq_len(n_show)], function(f) {
        sprintf("<li><strong>%s</strong> (test %s): %s</li>",
                if (!is.null(f$measure)) f$measure else if (!is.null(f$metric)) f$metric else "unknown",
                f$test_id, f$reason)
      }, character(1))
      remaining <- length(data$failures) - n_show
      extra <- if (remaining > 0) sprintf("<li>... and %d more</li>", remaining) else ""
      html <- paste0(html, sprintf("<ul>\n%s\n%s</ul>\n",
                                   paste(fail_items, collapse = "\n"), extra))
    }
  }

  # R session info
  html <- paste0(html,
    "<h2>Environment</h2>\n",
    '<div class="config-box">',
    sprintf("<strong>R:</strong> <code>%s</code> &nbsp;|&nbsp; ", R.version.string),
    sprintf("<strong>igraph:</strong> <code>%s</code> &nbsp;|&nbsp; ",
            tryCatch(as.character(packageVersion("igraph")), error = function(e) "N/A")),
    sprintf("<strong>cograph:</strong> <code>%s</code> &nbsp;|&nbsp; ",
            tryCatch(as.character(packageVersion("cograph")), error = function(e) "dev")),
    sprintf("<strong>Platform:</strong> <code>%s</code>",
            paste(Sys.info()[c("sysname", "release")], collapse = " ")),
    "</div>\n"
  )

  html <- paste0(html, html_tail())
  writeLines(html, out)
  cat("  [OK] Combined dashboard:", out, "\n")
  invisible(out)
}


# ============================================================================
# Main
# ============================================================================

cat("=" |> rep(70) |> paste(collapse = ""), "\n")
cat("GENERATING HTML VALIDATION REPORTS\n")
cat("=" |> rep(70) |> paste(collapse = ""), "\n\n")

generate_centrality_report()
generate_communities_report()
generate_network_properties_report()
generate_combined_report()

cat("\nDone.\n")
